### ISSUE TITLE
Link to the fork for size 2

### ISSUE THREAD

**Issue by adriantoine** [sindresorhus/tab-size-on-github#10]
Hi!

I just made a fork for a size 2 tab: https://github.com/adriantoine/tab-size-on-github. I just changed the size 4 to size 2, I changed the name and the logo to avoid confusions on the Chrome/Opera store. Could you tell me if there's a license issue since I just tweaked your logo and plugin? And if everything's ok, would you consider adding a link in your readme to my fork?

Thanks!

**Comment by sindresorhus** [comment]
All fine, but not interested in linking to it as I don't see the point of your fork.
